services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=shoppyis
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
        ports:
            - 5434:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 5050:80

volumes:
    pgdata: {}
